# Generated by Django 2.2 on 2019-06-25 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('diagnosis_name', models.CharField(max_length=150, null=True)),
                ('filler', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prac_icf',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proto.User')),
                ('body', models.TextField(max_length=1000, null=True)),
                ('activity', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
