# Generated by Django 2.2 on 2019-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prac_icf',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
